# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOl2YTgHYCGinxMA_wvj-k4SSdmi_p12
"""

# Personal Finance Chatbot using IBM Granite 3.3-2B Instruct
# Complete single-cell implementation for Google Colab

# Install required packages
!pip install -q transformers accelerate torch gradio

import gradio as gr
from transformers import pipeline
import torch
from datetime import datetime
import json

# Initialize the IBM Granite model
print("Loading IBM Granite 3.3-2B Instruct model...")
device = "cuda" if torch.cuda.is_available() else "cpu"
pipe = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct",
    device=device,
    max_new_tokens=512,
    temperature=0.7,
    top_p=0.9
)
print(f"Model loaded successfully on {device}!")

# User profiles storage
user_profiles = {}

# Financial knowledge base
FINANCIAL_CONTEXT = """
You are a helpful Personal Finance Assistant powered by IBM Granite AI. You provide:
- Personalized financial guidance on savings, taxes, and investments
- Budget analysis and summaries
- Spending insights and optimization suggestions
- Demographic-aware advice (students vs professionals)

Key principles:
- For students: Use simple language, focus on budgeting basics, student loans, part-time income
- For professionals: Use financial terminology, discuss investments, tax optimization, retirement planning
- Always provide actionable, practical advice
- Be encouraging and supportive
"""

def create_budget_summary(income, expenses, user_type):
    """Generate AI-powered budget summary"""

    prompt = f"""Based on the following financial data, generate a detailed budget summary:
- Monthly Income: ${income}
- Monthly Expenses: ${expenses}
- User Type: {user_type}
- Savings: ${income - expenses}

Provide:
1. Budget health assessment
2. Savings rate analysis
3. {'Student-specific' if user_type == 'Student' else 'Professional'} recommendations
4. Action items

Keep it concise and actionable."""

    messages = [
        {"role": "system", "content": FINANCIAL_CONTEXT},
        {"role": "user", "content": prompt}
    ]

    response = pipe(messages)
    return response[0]['generated_text'][-1]['content']

def get_spending_insights(spending_data, user_type):
    """Generate spending insights and suggestions"""

    prompt = f"""Analyze this spending pattern for a {user_type}:
{spending_data}

Provide:
1. Top spending categories
2. Areas for potential savings
3. {'Student budget' if user_type == 'Student' else 'Professional financial'} optimization tips
4. Specific actionable suggestions

Be specific and practical."""

    messages = [
        {"role": "system", "content": FINANCIAL_CONTEXT},
        {"role": "user", "content": prompt}
    ]

    response = pipe(messages)
    return response[0]['generated_text'][-1]['content']

def get_financial_advice(question, user_type, chat_history):
    """Main chatbot function with demographic-aware responses"""

    # Build context from chat history
    messages = [{"role": "system", "content": FINANCIAL_CONTEXT}]

    # Add chat history
    for human, assistant in chat_history:
        messages.append({"role": "user", "content": human})
        messages.append({"role": "assistant", "content": assistant})

    # Add current question with user type context
    user_context = f"[User Type: {user_type}] {question}"
    messages.append({"role": "user", "content": user_context})

    # Generate response
    response = pipe(messages)
    bot_response = response[0]['generated_text'][-1]['content']

    # Update chat history
    chat_history.append((question, bot_response))

    return "", chat_history

def generate_budget_interface(income, expenses, user_type):
    """Interface function for budget summary generation"""
    if not income or not expenses:
        return "⚠️ Please enter both income and expenses values."

    try:
        income_val = float(income)
        expenses_val = float(expenses)

        if income_val < 0 or expenses_val < 0:
            return "⚠️ Please enter positive values."

        summary = create_budget_summary(income_val, expenses_val, user_type)

        result = f"""
📊 **BUDGET SUMMARY**
{'='*50}
💰 Monthly Income: ${income_val:,.2f}
💸 Monthly Expenses: ${expenses_val:,.2f}
💵 Monthly Savings: ${income_val - expenses_val:,.2f}
📈 Savings Rate: {((income_val - expenses_val) / income_val * 100):.1f}%

{'='*50}

{summary}
"""
        return result
    except ValueError:
        return "⚠️ Please enter valid numeric values."

def generate_spending_analysis(food, transport, entertainment, utilities, other, user_type):
    """Interface function for spending insights"""
    try:
        categories = {
            "Food & Dining": float(food or 0),
            "Transportation": float(transport or 0),
            "Entertainment": float(entertainment or 0),
            "Utilities": float(utilities or 0),
            "Other": float(other or 0)
        }

        total = sum(categories.values())

        if total == 0:
            return "⚠️ Please enter at least one spending category."

        spending_breakdown = "\n".join([f"- {cat}: ${amt:,.2f} ({amt/total*100:.1f}%)"
                                        for cat, amt in categories.items() if amt > 0])

        spending_data = f"Total Monthly Spending: ${total:,.2f}\n\nBreakdown:\n{spending_breakdown}"

        insights = get_spending_insights(spending_data, user_type)

        result = f"""
💳 **SPENDING ANALYSIS**
{'='*50}
{spending_data}

{'='*50}

{insights}
"""
        return result
    except ValueError:
        return "⚠️ Please enter valid numeric values."

# Create Gradio Interface
with gr.Blocks(title="Personal Finance Chatbot", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 🏦 Personal Finance Chatbot
    ### Powered by IBM Granite 3.3-2B Instruct AI

    Get personalized financial guidance, budget summaries, and spending insights tailored to your profile.
    """)

    with gr.Row():
        user_type = gr.Radio(
            choices=["Student", "Professional"],
            value="Professional",
            label="👤 Select Your Profile",
            info="This helps tailor advice to your financial situation"
        )

    with gr.Tabs():
        # Tab 1: Chat Interface
        with gr.Tab("💬 Financial Chat"):
            gr.Markdown("Ask any questions about savings, taxes, investments, or general financial advice.")

            chatbot = gr.Chatbot(
                label="Chat History",
                height=400,
                bubble_full_width=False
            )

            with gr.Row():
                msg = gr.Textbox(
                    label="Your Question",
                    placeholder="E.g., How should I start investing? What's a good emergency fund?",
                    scale=4
                )
                submit_btn = gr.Button("Send", variant="primary", scale=1)

            gr.Examples(
                examples=[
                    "How much should I save for retirement?",
                    "What's the best way to create a budget?",
                    "How can I reduce my tax liability?",
                    "Should I invest in stocks or bonds?",
                    "What's a good emergency fund size?"
                ],
                inputs=msg
            )

            clear_btn = gr.Button("Clear Chat")

        # Tab 2: Budget Summary
        with gr.Tab("📊 Budget Summary"):
            gr.Markdown("Generate an AI-powered analysis of your monthly budget.")

            with gr.Row():
                with gr.Column():
                    budget_income = gr.Number(label="💰 Monthly Income ($)", value=5000)
                    budget_expenses = gr.Number(label="💸 Monthly Expenses ($)", value=3500)
                    budget_user_type = gr.Radio(
                        choices=["Student", "Professional"],
                        value="Professional",
                        label="Profile Type"
                    )
                    budget_btn = gr.Button("Generate Budget Summary", variant="primary")

                with gr.Column():
                    budget_output = gr.Textbox(
                        label="Budget Analysis",
                        lines=15,
                        max_lines=20
                    )

        # Tab 3: Spending Insights
        with gr.Tab("💳 Spending Insights"):
            gr.Markdown("Get personalized insights on your spending patterns.")

            with gr.Row():
                with gr.Column():
                    spending_food = gr.Number(label="🍔 Food & Dining ($)", value=500)
                    spending_transport = gr.Number(label="🚗 Transportation ($)", value=300)
                    spending_entertainment = gr.Number(label="🎬 Entertainment ($)", value=200)
                    spending_utilities = gr.Number(label="💡 Utilities ($)", value=400)
                    spending_other = gr.Number(label="📦 Other ($)", value=600)
                    spending_user_type = gr.Radio(
                        choices=["Student", "Professional"],
                        value="Professional",
                        label="Profile Type"
                    )
                    spending_btn = gr.Button("Analyze Spending", variant="primary")

                with gr.Column():
                    spending_output = gr.Textbox(
                        label="Spending Analysis",
                        lines=15,
                        max_lines=20
                    )

    # Event handlers
    submit_btn.click(
        get_financial_advice,
        inputs=[msg, user_type, chatbot],
        outputs=[msg, chatbot]
    )

    msg.submit(
        get_financial_advice,
        inputs=[msg, user_type, chatbot],
        outputs=[msg, chatbot]
    )

    clear_btn.click(lambda: None, None, chatbot, queue=False)

    budget_btn.click(
        generate_budget_interface,
        inputs=[budget_income, budget_expenses, budget_user_type],
        outputs=budget_output
    )

    spending_btn.click(
        generate_spending_analysis,
        inputs=[spending_food, spending_transport, spending_entertainment,
                spending_utilities, spending_other, spending_user_type],
        outputs=spending_output
    )

    gr.Markdown("""
    ---
    ### 📝 Features:
    - **Personalized Advice**: Tailored to students or professionals
    - **Budget Summaries**: AI-generated financial health assessments
    - **Spending Insights**: Actionable recommendations to optimize expenses
    - **Natural Conversations**: Context-aware financial guidance

    *Powered by IBM Granite 3.3-2B Instruct Model*
    """)

# Launch the app
print("\n" + "="*50)
print("🚀 Starting Personal Finance Chatbot...")
print("="*50 + "\n")

demo.launch(share=True, debug=True)